### ISSUE TITLE
Manque variable de subtitution

### ISSUE THREAD

**Issue by lmag** [Evarisk/Projets-developpement#38]
Dans la masse action du mail de facturation

![Image](https://github.com/Evarisk/Projets-developpement/assets/3288514/f4d08057-1b6d-4d69-9cc5-63ece9a38b25)

![Image](https://github.com/Evarisk/Projets-developpement/assets/3288514/729d7fd1-27a3-475a-8845-406cbf865610)

Manque var de substitution de lien de paiement

**Comment by evarisk-micka** [comment]
https://github.com/Dolibarr/dolibarr/issues/26676
